### ISSUE TITLE
Wrong comment in exit() function

### ISSUE THREAD

**Issue by yh36** [discovery-unicamp/ale-exercise-book#1]
Is it a typo for the comment of "syscall exit (64)"? Do you mean "93" instead of "64"?
```
void exit(int code)
{
  __asm__ __volatile__(
    "mv a0, %0           # return code\n"
    "li a7, 93           # syscall exit (64) \n"
```

**Comment by eborin** [comment]
Dear Yi Hou,

indeed, it is a type in the comment. The correct code is 93. I'll fix it.

I'm assuming you found this on the exercise book (
https://riscv-programming.org/ale-exercise-book/book/ch01-01-code-generation-tools.html).
Please, let me know if you find this issue on the book.

Regards,

--
Prof. Edson Borin
Institute of Computing
Unicamp


Em dom., 18 de ago. de 2024 às 20:27, Yi Hou ***@***.***>
escreveu:

**Comment by yh36** [comment]
Hi Edson,

1. Yes, the typo occurs on the exercise book. Currently I see this issue on Exercise 1.1 and Exercise 2.2.
2. I also saw a warning when I compiled my simple calculator program on Exercise 2.2, as shown below,
```
    $ riscv64-unknown-elf-gcc -mabi=ilp32 -march=rv32i -S simple_calc.c -o simple_calc.s
simple_calc.c: In function 'exit':
simple_calc.c:13:1: warning: 'noreturn' function does return
   13 | }
      | ^
```

I am not sure if this warning is caused by `ecall`, which might return something but `exit()` expects no return. This compilation warning also shows up in Exercise 1.1. I attached my code for your reference.
[simple_calc.c.txt](https://github.com/user-attachments/files/16662987/simple_calc.c.txt)

3. I saw inconsistent behavior when I ran my *simple_calc.c* on Exercise 2.2. The first time gave me *Fails* on test 8 and 13. Then I passed all tests after I reran my code.
4. Do you have solution link for this exercise book?

Regards,
Yi

**Comment by yh36** [comment]
There is another comment typo in Exercise 3.1. 
```
int read(int __fd, const void *__buf, int __n){
    int ret_val;
  __asm__ __volatile__(
    "mv a0, %1           # file descriptor\n"
    "mv a1, %2           # buffer \n"
    "mv a2, %3           # size \n"
    "li a7, 63           # syscall write code (63) \n"      <== SHOULD be "read" code instead of "write"
```

**Comment by eborin** [comment]
Dear Yi Hou,

thank you again! We shall fix the typo.

Regards,

--
Prof. Edson Borin
Institute of Computing
Unicamp


Em ter., 20 de ago. de 2024 às 16:31, Yi Hou ***@***.***>
escreveu:
